ERROR:root:Logging with exception info
Traceback (most recent call last):
  File "/Users/jstrick/Desktop/py3master/EXAMPLES/logging_exception.py", line 12, in <module>
    result = i/0
ZeroDivisionError: division by zero
ERROR:root:Logging with exception info
Traceback (most recent call last):
  File "/Users/jstrick/Desktop/py3master/EXAMPLES/logging_exception.py", line 12, in <module>
    result = i/0
ZeroDivisionError: division by zero
ERROR:root:Logging with exception info
Traceback (most recent call last):
  File "/Users/jstrick/Desktop/py3master/EXAMPLES/logging_exception.py", line 12, in <module>
    result = i/0
ZeroDivisionError: division by zero
